version: "3"

services:
  core-keeper:
    image: escaping/core-keeper-dedicated
    volumes:
      - /home/stake/containers/core-keeper/server-files:/home/steam/core-keeper-dedicated
      - /home/stake/containers/core-keeper/server-data:/home/steam/core-keeper-data
    env_file:
      - stack.env
    restart: unless-stopped
    stop_grace_period: 2m

