version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    environment:
      - TZ=America/New_York
    network_mode: 'host'
    volumes:
      - /home/stake/containers/jellyfin/config:/config
      - /home/stake/containers/jellyfin/config:/cache
      - /home/stake/usb_mount/media_storage/media:/media
    restart: 'unless-stopped'
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"

